:beers: Fix linking error in demos
The link errors are due to the lack of an
`initalize_platform(resource_map&)` function within the `lpc4078.cpp`
file. What was there was `initalize_platform(resource_map)`. Notice
the lack of a `&`. Yeah, since that function didn't show up in link
resolution, I be the whole file got dropped. If it had just said:

```
undefined reference to `initialize_platform(resource_list&)'
```

I would have tracked down the error. That is one annoyance with
LTO. You get bizarre linking errors due to how dependency resolve
themselves.